# Generated by Django 3.0.2 on 2020-01-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAccountInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
    ]
