# Generated by Django 3.0.2 on 2020-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Date sent')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full name')),
                ('email_address', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject')),
                ('message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Message')),
            ],
        ),
    ]
